apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigma-{{ .Chart.Name }}-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-server
          image: sigma-auth:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /auth/data
              name: data
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: sigma-{{ .Chart.Name }}-jwt-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sigma-{{ .Chart.Name }}-pvc
