apiVersion: v1
kind: Service
metadata:
  name: "{name}-redis"
spec:
  selector:
    app: inference-backend-redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
