apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{name}-redis"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-backend-redis
  template:
    metadata:
      labels:
        app: inference-backend-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
