apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sergiorivera50/thesis-auth:latest
          volumeMounts:
            - name: data
              mountPath: "/auth/data"
              subPath: auth.db
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: auth-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth-pvc
