version: '3'
services:
  auth:
    build: services/auth
    ports:
      - "4000:4000"
    command: flask run --host 0.0.0.0 --port 4000
    volumes:
      - ./services/auth/app:/auth/app
      - ./services/auth/data:/auth/data
      - ./services/auth/requirements.txt:/auth/requirements.txt
      - ./services/auth/handlers.py:/auth/handlers.py
    environment:
      FLASK_DEBUG: 1
    env_file:
      - "services/auth/.env"

  registry:
    build: services/registry
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000
    volumes:
      - ./services/registry/app:/registry/app
      - ./services/registry/requirements.txt:/registry/requirements.txt
      - ./services/registry/handlers.py:/registry/handlers.py
    environment:
      FLASK_DEBUG: 1
    env_file:
      - "services/registry/.env"

  inference:
    build: services/inference
    ports:
      - "3000:3000"
    command: flask run --host 0.0.0.0 --port 3000
    volumes:
      - ./services/inference/app:/inference/app
      - ./services/inference/requirements.txt:/inference/requirements.txt
      - ./services/inference/handlers.py:/inference/handlers.py
    environment:
      MODEL_ID: 6405c0d3fae11e44160f719b
      FLASK_DEBUG: 1
    env_file:
      - "services/inference/.env"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
