version: '3'
services:
  gateway:
    build: services/gateway
    ports:
      - "8000:8000"
    command: flask run --host 0.0.0.0 --port 8000
    volumes:
      - ./services/gateway/app:/gateway/app
      - ./services/gateway/requirements.txt:/gateway/requirements.txt
    environment:
      FLASK_DEBUG: 1
    env_file:
      - "services/gateway/.env"
  auth:
    build: services/auth
    ports:
      - "4000:4000"
    command: flask run --host 0.0.0.0 --port 4000
    volumes:
      - ./services/auth/app:/auth/app
      - ./services/auth/data:/auth/data
      - ./services/auth/requirements.txt:/auth/requirements.txt
    environment:
      FLASK_DEBUG: 1
    env_file:
      - "services/auth/.env"
  registry:
    build: services/registry
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000
    volumes:
      - ./services/registry/app:/registry/app
      - ./services/registry/requirements.txt:/registry/requirements.txt
    environment:
      FLASK_DEBUG: 1
    env_file:
      - "services/registry/.env"
  inference:
    build: services/inference
    ports:
      - "3000:3000"
    command: flask run --host 0.0.0.0 --port 3000
    volumes:
      - ./services/inference/app:/inference/app
      - ./services/inference/requirements.txt:/inference/requirements.txt
    environment:
      MODEL_ID: 64060f8e547d5d27345c87cc
      FLASK_DEBUG: 1
    env_file:
      - "services/inference/.env"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
