apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferencebackends.inference.sigma.com
spec:
  group: inference.sigma.com
  names:
    kind: InferenceBackend
    plural: inferencebackends
    singular: inferencebackend
    shortNames:
      - ib
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                modelId:
                  type: string
                mongoHost:
                  type: string
                mongoDatabase:
                  type: string
                registryHost:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
