apiVersion: v1
kind: Service
metadata:
  name: sigma-{{ .Chart.Name }}-service
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
