apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigma-{{ .Chart.Name }}-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      serviceAccountName: sigma-registry-account
      containers:
        - name: registry-server
          image: sigma-registry:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mongodb-secret
