apiVersion: v1
kind: Service
metadata:
  name: sigma-{{ .Chart.Name }}-service
spec:
  selector:
    app: registry
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
